# Configuração para Deploy na Render
# Este arquivo contém as configurações necessárias para deploy na Render

# Build Command
pip install -r requirements.txt

# Start Command
gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 30 --access-logfile - app:app

# Environment Variables necessárias:
# FLASK_ENV=production
# PUBLIC_KEY=sua_chave_publica_duckfy
# SECRET_KEY=sua_chave_secreta_duckfy

# Versão do Python
python-3.11.x
